import test from 'node:test';import assert from 'node:assert/strict';
let catalog;try{catalog=await import('../curriculum.mjs')}catch{}
test('three difficulty levels contain 108 distinct authored decisions',()=>{
 assert.ok(catalog,'New curriculum module is missing');const seen=new Set();
 for(const level of catalog.difficulties){const missions=catalog.missionsFor(level.id);assert.equal(missions.length,12);for(const m of missions){assert.equal(m.steps.length,3);for(const step of m.steps){assert.ok(!seen.has(step.message),'Repeated decision: '+step.message);seen.add(step.message);assert.equal(step.choices.length,3);assert.equal(step.choices.filter(c=>c.score.every(n=>n===3)).length,1);for(const c of step.choices){assert.equal(c.score.length,3);assert.ok(c.score.every(n=>Number.isInteger(n)&&n>=0&&n<=3));assert.ok(c.feedback.length>60);assert.ok(c.text.length>20);}}}}assert.equal(seen.size,108);
});
test('length and source-position shortcuts stay below 80 percent at every difficulty',()=>{
 assert.ok(catalog,'New curriculum module is missing');for(const level of catalog.difficulties){const steps=catalog.missionsFor(level.id).flatMap(s=>s.steps);for(const metric of [c=>c.text.length,c=>c.text.match(/\S+/g).length])for(const direction of [Math.max,Math.min]){let total=0;for(const st of steps){const n=direction(...st.choices.map(metric));const tied=st.choices.filter(c=>metric(c)===n);total+=Math.max(...tied.map(c=>c.score.reduce((a,b)=>a+b,0)));}assert.ok(total/(steps.length*9)<.8,level.id+' length shortcut: '+total);}for(let i=0;i<3;i++){const total=steps.reduce((n,st)=>n+st.choices[i].score.reduce((a,b)=>a+b,0),0);assert.ok(total/(steps.length*9)<.8,level.id+' position '+i);}}
});
test('rubrics can distinguish weaknesses in every dimension, not always action',()=>{assert.ok(catalog,'New curriculum module is missing');for(const l of catalog.difficulties){const choices=catalog.missionsFor(l.id).flatMap(m=>m.steps.flatMap(s=>s.choices));for(let d=0;d<3;d++)assert.ok(choices.filter(c=>c.score.every((n,i)=>i===d||n>c.score[d])).length>=3,l.id+' lacks independent weakness in dimension '+d);}});
test('decision ordinal does not reveal a correct length rank or source position',()=>{assert.ok(catalog,'New curriculum module is missing');for(const l of catalog.difficulties)for(let ordinal=0;ordinal<3;ordinal++){const steps=catalog.missionsFor(l.id).map(s=>s.steps[ordinal]);for(const metric of [c=>c.text.length,c=>c.text.match(/\S+/g).length])for(const direction of [Math.max,Math.min]){const score=steps.reduce((n,st)=>n+Math.max(...st.choices.filter(c=>metric(c)===direction(...st.choices.map(metric))).map(c=>c.score.reduce((a,b)=>a+b,0))),0);assert.ok(score/(12*9)<.8,l.id+' ordinal '+ordinal+' length '+score);}for(let i=0;i<3;i++){const score=steps.reduce((n,st)=>n+st.choices[i].score.reduce((a,b)=>a+b,0),0);assert.ok(score/(12*9)<.8,l.id+' ordinal '+ordinal+' position '+i);}}});
test('unauthorised actions and unsupported incident claims earn little action-risk credit',()=>{assert.ok(catalog);for(const [id,level,step,choice] of [['handover','expert',1,0],['async','advanced',1,2],['payment','advanced',2,2],['incident','beginner',0,0],['async','expert',1,1]]){const c=catalog.missionFor(id,level).steps[step].choices[choice];assert.ok(c.score[2]<=1,id+' '+level+' dangerous action over-credit: '+c.score[2]);}});
