import test from 'node:test';import assert from 'node:assert/strict';import {freshState,readState} from '../core.mjs';import {validateProgress} from '../practice.mjs';import {scenarios,phrases} from '../scenarios.mjs';
let learning;try{learning=await import('../learning.mjs')}catch{}
const fixture=()=>({version:1,active:'requirements',answers:{requirements:[1,0]},history:[{id:'negotiation',at:1700000000000,choices:[1,0,2]}],reviews:{[phrases[0].id]:{rating:'good',due:1700000000000,interval:1,reviewedAt:1699900000000}},drafts:{builder:'Keep my draft',requirements:'Legacy email'}});
test('v1 backup migrates to legacy without granting new difficulty mastery',()=>{const s=readState(JSON.stringify(fixture()));assert.equal(s.version,2);assert.deepEqual(s.answers.requirements,[1,0]);assert.equal(s.history.length,1);assert.equal(s.drafts.builder,'Keep my draft');assert.equal(Object.keys(s.reviews).length,1);assert.equal(s.difficulty,'beginner');for(const l of ['beginner','advanced','expert'])assert.equal(Object.values(s.levels[l].answers).flat().length,0);assert.deepEqual(validateProgress(JSON.stringify(fixture())),s)});
test('canonical answers and shuffled orders survive resume, export and retries by level',()=>{assert.ok(learning,'Learning module missing');const s=freshState();learning.prepareAttempt(s,'requirements','advanced',()=>.2);const orders=structuredClone(s.levels.advanced.orders.requirements);assert.ok(orders.every(o=>new Set(o).size===3));learning.recordChoice(s,'requirements','advanced',orders[0][1],1700000000000);learning.prepareAttempt(s,'requirements','advanced',()=>.9);assert.deepEqual(s.levels.advanced.orders.requirements,orders);assert.equal(s.levels.beginner.answers.requirements.length,0);assert.deepEqual(readState(JSON.stringify(s)),s);learning.recordChoice(s,'requirements','advanced',0,1700000000001);learning.recordChoice(s,'requirements','advanced',1,1700000000002);assert.equal(s.levels.advanced.history.length,1);learning.recordChoice(s,'requirements','advanced',2);assert.equal(s.levels.advanced.history.length,1);learning.prepareAttempt(s,'requirements','advanced',()=>.8,true);assert.equal(s.levels.advanced.answers.requirements.length,0);assert.equal(s.levels.advanced.history.length,1)});
test('profiles never fabricate absent skill scores and recommendations prefer partial work',()=>{assert.ok(learning,'Learning module missing');const s=freshState();assert.equal(learning.levelProfile(s,'expert').dimensions,null);assert.equal(learning.levelProfile(s,'expert').attempts,0);learning.prepareAttempt(s,'payment','expert',()=>.1);learning.recordChoice(s,'payment','expert',0);assert.equal(learning.recommendForLevel(s,'expert').id,'payment');assert.equal(learning.levelProfile(s,'beginner').completed,0);});
test('v2 corrupt saved permutations recover without reinterpreting canonical choices',()=>{assert.ok(learning,'Learning module missing');const s=freshState();learning.prepareAttempt(s,'requirements','expert',()=>.2);s.levels.expert.answers.requirements=[2,0];s.levels.expert.orders.requirements=[[0,0,2],[1,2,0],[0,1,2]];const loaded=readState(JSON.stringify(s));assert.deepEqual(loaded.levels.expert.answers.requirements,[2,0]);assert.deepEqual(loaded.levels.expert.orders.requirements[0],[0,1,2]);assert.equal(loaded.levels.expert.history.length,0);});

test('malformed v2 backup cannot silently replace profiles with empty data',()=>{const s=freshState();s.levels=null;assert.throws(()=>validateProgress(JSON.stringify(s)),/profiles/)});
test('retry keeps last completed skill evidence until the next attempt finishes',()=>{assert.ok(learning);const s=freshState();learning.prepareAttempt(s,'requirements','advanced',()=>.3);for(let i=0;i<3;i++)learning.recordChoice(s,'requirements','advanced',0,1700000000000+i);const previous=learning.levelProfile(s,'advanced');assert.equal(previous.completed,1);learning.prepareAttempt(s,'requirements','advanced',()=>.2,true);learning.recordChoice(s,'requirements','advanced',2);assert.equal(learning.levelProfile(s,'advanced').completed,1);assert.deepEqual(learning.levelProfile(s,'advanced').dimensions,previous.dimensions);assert.deepEqual(learning.levelProfile(readState(JSON.stringify(s)),'advanced').dimensions,previous.dimensions);});
test('invalid and far-future dates cannot strand reviews or displace real history',()=>{const raw=fixture();raw.reviews[phrases[0].id].due=1e300;raw.history.push({id:'requirements',at:1e300,choices:[0,0,0]});const s=readState(JSON.stringify(raw));assert.equal(Object.keys(s.reviews).length,0);assert.equal(s.history.length,1);assert.equal(s.history[0].at,1700000000000);const v=freshState();v.levels.expert.history=[{id:'requirements',at:1e300,choices:[0,0,0]}];assert.equal(readState(JSON.stringify(v)).levels.expert.history.length,0)});
test('practice points are distinct from accuracy of selecting the best reply',async()=>{const {evaluate}=await import('../core.mjs');const {missionFor}=await import('../curriculum.mjs');const m=missionFor('requirements','expert');const choices=m.steps.map(st=>st.choices.findIndex(c=>!c.score.every(n=>n===3)));const score=evaluate(m,choices);assert.equal(score.bestCount,0);assert.equal(score.accuracy,0);assert.ok(score.total>0);const s=freshState();learning.prepareAttempt(s,m.id,'expert',()=>.2);choices.forEach((c,i)=>learning.recordChoice(s,m.id,'expert',c,1700000000000+i));assert.equal(learning.levelProfile(s,'expert').accuracy,0);assert.ok(learning.levelProfile(s,'expert').average>0)});
